#!/bin/bash

if [ "$(hostname -s)" == "core1" ]; then
    OTHER="172.16.1.101"
elif [ "$(hostname -s)" == "core2" ]; then
    OTHER="172.16.1.100"
else
    OTHER=""
fi

cp dhcpd.conf* /etc/dhcp
mv /etc/dhcp/dhcpd.conf.$(hostname -s) /etc/dhcp/dhcpd.conf
sudo systemctl restart isc-dhcp-server.service

if [ "$OTHER"x != "x" ]; then
    scp dhcpd.conf* ${OTHER}:/etc/dhcp
    ssh $OTHER rm /etc/dhcp/dhcpd.conf.core1
    ssh $OTHER mv /etc/dhcp/dhcpd.conf.core2 /etc/dhcp/dhcpd.conf
    ssh $OTHER -t sudo systemctl restart isc-dhcp-server.service
fi
